# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0xfcf8fdff
bordercolor = 0x777680ff
focuscolor = 0x4d57a9ff
maximizescreencolor = 0x5b5d72ff
urgentcolor = 0xba1a1aff
scratchpadcolor = 0x77536cff
globalcolor = 0xdfe0ffff
overlaycolor = 0xe0e0f9ff
