# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131316ff
bordercolor = 0x91909aff
focuscolor = 0xbdc2ffff
maximizescreencolor = 0xc4c4ddff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe7b9d6ff
globalcolor = 0x353e90ff
overlaycolor = 0x444559ff
