# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "zswap.enabled=0" ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 100;
    "vm.page-cluster" = 0;
  };
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e622450d-2f14-4483-ade0-aa4b5a980a8d";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e622450d-2f14-4483-ade0-aa4b5a980a8d";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/e622450d-2f14-4483-ade0-aa4b5a980a8d";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd:3" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FA8B-4A16";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/nvme0n1p3" = {
    device = "/dev/disk/by-uuid/7C920798920755D4";
    fsType = "ntfs-3g";
    options =
      [ "rw" "uid=1001" "gid=100" "dmask=000" "fmask=000" "x-gvfs-show" ];
  }; # Windows
  #在 configuration.nix 中配置自动挂载后，这些分区被视为"系统分区"而不是"可移动设备"
  #Nautilus 就不会在侧边栏显示它们了。
  #解决方案：添加 x-gvfs-show 选项，让Nautilus 显示这些挂载点

  fileSystems."/mnt/nvme0n1p4" = {
    device = "/dev/disk/by-uuid/9FAB0FC4562CB861";
    fsType = "ntfs-3g";
    options =
      [ "rw" "uid=1001" "gid=100" "dmask=000" "fmask=000" "x-gvfs-show" ];
  }; # SSD

  fileSystems."/mnt/dev/sda2" = {
    device = "/dev/disk/by-uuid/18C64E6FC64E4CE6";
    fsType = "ntfs-3g";
    options =
      [ "rw" "uid=1001" "gid=100" "dmask=000" "fmask=000" "x-gvfs-show" ];
  }; # HDD

  swapDevices =
    [{ device = "/dev/disk/by-uuid/642ce81b-8107-45d9-adc8-d054491dedae"; }];
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
    priority = 100;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  # TODO: Enabling Intel microcode currently prevents this machine from booting.
  # Keep it disabled for now and investigate the firmware/boot issue separately.
  hardware.cpu.intel.updateMicrocode = false;
}
